version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gobarber
      POSTGRES_PASSWORD: gobarber
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
